// Generated by AI

(async function () {
    // ==========================================
    // 提案機能の組み込み (バトルルーム用)
    // ==========================================
    const proposeMovie = function (movieId) {
        const controllerName = "battle-room";
        const selector = `[data-controller~="${controllerName}"]`;
        const element = document.querySelector(selector);

        if (!element) {
            console.error("エラー: コントローラーが見つかりません。");
            return;
        }

        const stimApp = window.application || window.Stimulus;

        try {
            const controller = stimApp.getControllerForElementAndIdentifier(element, controllerName);

            // 1. 本物のボタン要素を作成して、必要なデータをセット
            const dummyButton = document.createElement('button');
            dummyButton.dataset.movieId = String(movieId);

            // 2. classList.add('...') などが実行されてもエラーにならないよう空の関数を準備
            // (本物の要素なので classList は持っていますが、念のため)

            // 3. Stimulusが期待する形式のイベントオブジェクトを作成
            const fakeEvent = {
                currentTarget: dummyButton,
                target: dummyButton,
                preventDefault: () => { },
                stopPropagation: () => { }
            };

            // 4. 実行
            controller.proposeSongFromSearch(fakeEvent);
            console.log(`✅ Movie ID: ${movieId} を送信しました（エラー回避モード）`);

        } catch (e) {
            console.error("実行エラーが発生しました:", e);
            console.log("ヒント: 画面上に検索結果が一度も出ていないと、内部のTarget参照で落ちる場合があります。");
        }
    };

    // ==========================================
    // UI基盤: モーダル表示モジュール
    // ==========================================
    const showModal = (options) => {
        return new Promise((resolve) => {
            const overlay = document.createElement('div');
            overlay.style.cssText = 'position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(0,0,0,0.5);z-index:2147483647;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(2px);';
            const box = document.createElement('div');
            box.style.cssText = 'background:#fff;padding:24px;border-radius:12px;box-shadow:0 10px 25px rgba(0,0,0,0.2);min-width:320px;max-width:90%;text-align:center;font-family:sans-serif;color:#333;box-sizing:border-box;';

            if (options.title) {
                const title = document.createElement('h4');
                title.textContent = options.title;
                title.style.cssText = 'margin:0 0 15px 0;font-size:1.2rem;font-weight:bold;color:#212529;';
                box.appendChild(title);
            }

            // ★ options.contentElement で自由にHTML要素を流し込めるように強化
            if (options.contentElement) {
                box.appendChild(options.contentElement);
            } else if (options.message) {
                const msg = document.createElement('p');
                msg.textContent = options.message;
                msg.style.cssText = 'margin:0 0 20px 0;font-size:0.95rem;color:#495057;line-height:1.5;text-align:left;white-space:pre-wrap;';
                box.appendChild(msg);
            }

            let input;
            if (options.type === 'prompt') {
                input = document.createElement('input');
                input.type = 'number'; input.min = '1'; input.max = '5'; input.value = options.defaultValue || '1';
                input.style.cssText = 'width:100%;padding:10px;margin-bottom:20px;box-sizing:border-box;border:1px solid #ced4da;border-radius:6px;font-size:1rem;text-align:center;outline:none;';
                box.appendChild(input);
            }

            const btnContainer = document.createElement('div');
            btnContainer.style.cssText = 'display:flex;justify-content:center;gap:10px;';

            if (options.type === 'prompt') {
                const btnCancel = document.createElement('button');
                btnCancel.textContent = 'キャンセル';
                btnCancel.style.cssText = 'padding:8px 20px;background:#6c757d;color:#fff;border:none;border-radius:6px;cursor:pointer;';
                btnCancel.onclick = () => { overlay.remove(); resolve(null); };
                btnContainer.appendChild(btnCancel);
            }
            const btnOk = document.createElement('button');
            btnOk.textContent = options.type === 'prompt' ? '決定' : 'OK';
            btnOk.style.cssText = 'padding:8px 24px;background:#0d6efd;color:#fff;border:none;border-radius:6px;cursor:pointer;font-weight:bold;';
            btnOk.onclick = () => { overlay.remove(); resolve(options.type === 'prompt' ? input.value : true); };

            btnContainer.appendChild(btnOk);
            box.appendChild(btnContainer);
            overlay.appendChild(box);
            document.body.appendChild(overlay);
            if (input) input.focus();
        });
    };

    // ==========================================
    // UI基盤: ローディング（ぐるぐる）モジュール ★新規追加
    // ==========================================
    let loadingOverlay = null;
    const showLoading = () => {
        if (!document.getElementById('tt-spin-css')) {
            const style = document.createElement('style');
            style.id = 'tt-spin-css';
            style.textContent = '@keyframes tt-spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }';
            document.head.appendChild(style);
        }

        loadingOverlay = document.createElement('div');
        loadingOverlay.style.cssText = 'position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(0,0,0,0.5);z-index:2147483647;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(2px);';

        const box = document.createElement('div');
        box.style.cssText = 'background:#fff;padding:24px;border-radius:12px;box-shadow:0 10px 25px rgba(0,0,0,0.2);min-width:320px;max-width:90%;text-align:center;font-family:sans-serif;color:#333;box-sizing:border-box;';

        const spinner = document.createElement('div');
        spinner.style.cssText = 'width:40px;height:40px;border:4px solid #e9ecef;border-top:4px solid #0d6efd;border-radius:50%;animation:tt-spin 1s linear infinite;margin:0 auto 15px auto;';
        box.appendChild(spinner);

        const title = document.createElement('h4');
        title.textContent = '検索中...';
        title.style.cssText = 'margin:0 0 10px 0;font-size:1.2rem;font-weight:bold;color:#212529;';
        box.appendChild(title);

        const msg = document.createElement('p');
        msg.textContent = 'ランダムに抽出・解析しています';
        msg.style.cssText = 'margin:0;font-size:0.95rem;color:#495057;';
        box.appendChild(msg);

        loadingOverlay.appendChild(box);
        document.body.appendChild(loadingOverlay);
    };

    const hideLoading = () => {
        if (loadingOverlay) {
            loadingOverlay.remove();
            loadingOverlay = null;
        }
    };

    // ==========================================
    // データ抽出モジュール (検索結果一覧用)
    // ==========================================
    const extractMovieData = (randomBox) => {
        let title = "タイトル不明";
        let titleEl = randomBox.querySelector(".movie-title-text");
        if (titleEl) title = titleEl.textContent.trim();

        let href = randomBox.hasAttribute("href") ? randomBox.getAttribute("href") : "";
        let fullUrl = href.startsWith("http") ? href : window.location.origin + href;
        let idMatch = href.match(/(\d+)$/);
        let id = idMatch ? idMatch[1] : null;

        let imgTag = randomBox.querySelector("img");
        let thumbUrl = imgTag ? imgTag.src : "";

        return { id, title, fullUrl, thumbUrl, linesStr: "不明", keysStr: "不明" };
    };

    // ==========================================
    // 詳細データ取得モジュール (行数・打鍵数)
    // ==========================================
    const fetchMovieDetails = async (movieId) => {
        let details = { linesStr: "不明", keysStr: "不明" };
        if (!movieId) return details;

        try {
            let res = await fetch(`/movie/show/${movieId}`);
            if (!res.ok) throw new Error("詳細ページの取得に失敗しました");
            let text = await res.text();
            let doc = new DOMParser().parseFromString(text, 'text/html');

            let descNode = doc.querySelector('.detail-description-text[data-movie-detail-target="descriptionText"]');
            if (descNode) {
                let descText = descNode.textContent || "";
                let lineMatch = descText.match(/全(\d+)行/);
                let keyMatch = descText.match(/打鍵数(\d+)/);

                if (lineMatch) details.linesStr = lineMatch[1] + " 行";
                if (keyMatch) details.keysStr = keyMatch[1] + " 打";
            }
        } catch (e) {
            console.warn(`ID: ${movieId} の詳細データ取得に失敗しました:`, e);
        }
        return details;
    };

    // ==========================================
    // 結果表示用のリッチDOM生成モジュール (非同期・API対応・音量操作付き)
    // ==========================================
    const buildRichContent = async (movieData, level) => {
        const contentDiv = document.createElement('div');
        contentDiv.style.cssText = 'text-align:left; background:#f8f9fa; padding:15px; border-radius:8px; margin-bottom:20px; font-size: 0.95rem; border: 1px solid #dee2e6;';

        if (movieData.thumbUrl) {
            const ytIdMatch = movieData.thumbUrl.match(/\/vi\/([a-zA-Z0-9_-]{11})\//);

            if (ytIdMatch && ytIdMatch[1]) {
                // YouTubeプレーヤーのラッパー
                const playerWrapper = document.createElement('div');
                playerWrapper.style.cssText = 'width:100%; height:200px; border-radius:6px; margin-bottom:8px; overflow:hidden; box-shadow:0 2px 5px rgba(0,0,0,0.1); background:#000;';

                const playerId = 'yt-player-' + Date.now();
                const playerDiv = document.createElement('div');
                playerDiv.id = playerId;
                playerWrapper.appendChild(playerDiv);
                contentDiv.appendChild(playerWrapper);

                // 音量操作用のスライダーUIを作成
                const volumeContainer = document.createElement('div');
                volumeContainer.style.cssText = 'display:flex; align-items:center; margin-bottom:12px; gap:10px; font-size:0.9rem; color:#495057;';

                const volLabel = document.createElement('strong');
                volLabel.textContent = '音量';
                volLabel.style.cssText = 'width: 70px; flex-shrink:0; color:#495057;';

                const volSlider = document.createElement('input');
                volSlider.type = 'range';
                volSlider.min = '0';
                volSlider.max = '100';
                volSlider.value = '50'; // 初期値50
                volSlider.style.cssText = 'flex-grow:1; cursor:pointer;';

                const volValue = document.createElement('span');
                volValue.textContent = '50%';
                volValue.style.cssText = 'width:35px; text-align:right; font-variant-numeric: tabular-nums;';

                volumeContainer.appendChild(volLabel);
                volumeContainer.appendChild(volSlider);
                volumeContainer.appendChild(volValue);
                contentDiv.appendChild(volumeContainer);

                // YouTube IFrame API の読み込みを待機 (安全対策で3秒のタイムアウトを追加)
                await new Promise((resolve) => {
                    if (window.YT && window.YT.Player) {
                        resolve();
                    } else {
                        const existingCallback = window.onYouTubeIframeAPIReady;
                        window.onYouTubeIframeAPIReady = () => {
                            if (existingCallback) existingCallback();
                            resolve();
                        };
                        if (!document.querySelector('script[src="https://www.youtube.com/iframe_api"]')) {
                            const tag = document.createElement('script');
                            tag.src = "https://www.youtube.com/iframe_api";
                            document.head.appendChild(tag);
                        }
                        // APIブロック対策（3秒経っても読めなければ進む）
                        setTimeout(resolve, 3000);
                    }
                });

                let ytPlayer;

                volSlider.oninput = (e) => {
                    const val = e.target.value;
                    volValue.textContent = val + '%';
                    if (ytPlayer && typeof ytPlayer.setVolume === 'function') {
                        ytPlayer.setVolume(val);
                    }
                };

                // モーダルが画面(DOM)に表示されるまで待ってからプレーヤーを初期化する
                if (window.YT && window.YT.Player) {
                    let attempts = 0;
                    const checkAndInitPlayer = () => {
                        // 画面上に target のIDが確実に出現したか確認
                        if (document.getElementById(playerId)) {
                            ytPlayer = new window.YT.Player(playerId, {
                                videoId: ytIdMatch[1],
                                width: '100%',
                                height: '100%',
                                playerVars: { 'rel': 0 },
                                events: {
                                    'onReady': (event) => {
                                        event.target.setVolume(parseInt(volSlider.value));
                                    }
                                }
                            });
                        } else if (attempts < 50) {
                            // まだDOMになければ50ミリ秒後に再チェック (最大約2.5秒待機)
                            attempts++;
                            setTimeout(checkAndInitPlayer, 50);
                        }
                    };
                    checkAndInitPlayer(); // チェック開始
                }

            } else {
                // YouTube以外の画像だった場合のフォールバック
                const imgEl = document.createElement('img');
                imgEl.src = movieData.thumbUrl;
                imgEl.style.cssText = 'width:100%; height:auto; max-height:180px; object-fit:cover; border-radius:6px; margin-bottom:12px; border:1px solid #ccc;';
                contentDiv.appendChild(imgEl);
            }
        }

        const appendRow = (label, valueEl) => {
            const row = document.createElement('div');
            row.style.cssText = 'display:flex; margin-bottom:6px; border-bottom:1px dashed #ced4da; padding-bottom:4px;';
            const strong = document.createElement('strong');
            strong.textContent = label;
            strong.style.cssText = 'width: 70px; flex-shrink:0; color:#495057;';
            row.appendChild(strong);
            const val = document.createElement('div');
            val.style.cssText = 'word-break: break-all;';
            val.appendChild(valueEl);
            row.appendChild(val);
            contentDiv.appendChild(row);
        };

        const lvSpan = document.createElement('span'); lvSpan.textContent = "Lv. " + level;
        appendRow("レベル", lvSpan);

        const statsSpan = document.createElement('span'); statsSpan.textContent = `${movieData.linesStr} / ${movieData.keysStr}`;
        appendRow("タイプ数", statsSpan);

        const idSpan = document.createElement('span'); idSpan.textContent = "#" + movieData.id;
        appendRow("ID", idSpan);

        const titleA = document.createElement('a');
        titleA.href = movieData.fullUrl; titleA.target = "_blank"; titleA.textContent = movieData.title;
        titleA.style.cssText = 'color:#0d6efd; text-decoration:none; font-weight:bold;';
        appendRow("タイトル", titleA);

        return contentDiv;
    };

    // ==========================================
    // メイン処理
    // ==========================================
    if (!window.location.href.includes("typing-tube.net")) {
        await showModal({ title: "エラー", message: "TypingTubeのサイト上で実行してください。" });
        return;
    }

    let lvStr = await showModal({ type: 'prompt', title: 'レベル選択', message: '検索するレベルを入力してください (1-5)', defaultValue: '1' });
    if (!lvStr) return;
    let lv = Math.max(1, Math.min(5, parseInt(lvStr) || 1));

    const origTitle = document.title;
    document.title = "🔄 抽出中...";

    // ★追加: 検索・解析が始まる直前にローディングモーダルを表示
    showLoading();

    try {
        let res1 = await fetch(`/search?lv=${lv}&page=1`);
        let text1 = await res1.text();
        let doc1 = new DOMParser().parseFromString(text1, 'text/html');

        let totalPages = 1;
        let pagination_counter = doc1.querySelector("div.pagination-counter");
        if (pagination_counter) {
            let matches = pagination_counter.innerText.match(/Page\s+\d+\s+\/\s+(\d+)/i);
            if (matches && matches[1]) totalPages = parseInt(matches[1]);
        }

        let targetPage = Math.floor(Math.random() * totalPages) + 1;
        let res2 = await fetch(`/search?lv=${lv}&page=${targetPage}`);
        let text2 = await res2.text();
        let doc2 = new DOMParser().parseFromString(text2, 'text/html');

        let boxes = doc2.querySelectorAll("a.movie-card");
        if (boxes.length === 0) {
            hideLoading(); // ★追加: エラー表示前にローディングを閉じる
            await showModal({ title: "結果", message: "アイテムが見つかりませんでした。" });
            return;
        }
        let randomBox = boxes[Math.floor(Math.random() * boxes.length)];

        // モジュールを利用して基本情報を抽出
        const movieData = extractMovieData(randomBox);
        if (!movieData.id) {
            hideLoading(); // ★追加: エラー表示前にローディングを閉じる
            await showModal({ title: "エラー", message: "IDを抽出できませんでした。" });
            return;
        }

        // 詳細ページをフェッチして行数・打鍵数を取得し、データをマージ
        const movieDetails = await fetchMovieDetails(movieData.id);
        movieData.linesStr = movieDetails.linesStr;
        movieData.keysStr = movieDetails.keysStr;

        // モジュールを利用してリッチなUIを構築 (非同期なのでawaitを追加)
        // ※ この処理中にYouTube APIのロード待ちも行われます
        const contentDiv = await buildRichContent(movieData, lv);

        // ==========================================
        // 提案機能とUI状態管理
        // ==========================================
        const statusMsg = document.createElement('p');
        statusMsg.style.cssText = `margin-top:12px; font-size:0.85rem; font-weight:bold; text-align:center; min-height:1.5em;`;
        contentDiv.appendChild(statusMsg);

        // 適切なページ（バトルルーム等）かどうかを判定する
        if (window.location.href.match(/typing-tube\.net\/battle\/\d+/)) {
            // モーダルのチャット提案ボタンを「曲を提案」ボタンとして再定義
            const proposeBtn = document.createElement('button');
            proposeBtn.textContent = "曲を提案";
            proposeBtn.style.cssText = "display:block; width:100%; padding:10px; margin-top:10px; background:#198754; color:#fff; border:none; border-radius:6px; cursor:pointer; font-size:1rem; font-weight:bold; transition:background 0.2s;";
            proposeBtn.onmouseover = () => { if (!proposeBtn.disabled) proposeBtn.style.background = "#157347"; };
            proposeBtn.onmouseout = () => { if (!proposeBtn.disabled) proposeBtn.style.background = "#198754"; };

            proposeBtn.onclick = () => {
                // 提案APIを叩く
                proposeMovie(movieData.id);

                // チャット欄への書き込みと送信を同時に行う
                const chatInput = document.querySelector(".room-chat-input");
                const sendBtn = document.querySelector(".room-chat-send-btn");

                if (chatInput && sendBtn) {
                    // 入力欄に規定のフォーマットで文字列をセット
                    chatInput.value = `[Random API] Lv.${lv} #${movieData.id} - ${movieData.title} (${movieData.fullUrl})`;

                    // サイト側のJSフレームワーク（Stimulusなど）に入力変更を検知させるためのイベント発火
                    chatInput.dispatchEvent(new Event('input', { bubbles: true }));

                    // 送信ボタンをクリック
                    sendBtn.click();
                } else {
                    console.warn("チャット欄が見つかりません。（バトルルーム外の可能性があります）");
                }

                // ボタンの無効化（二重提案防止）とUI更新
                proposeBtn.disabled = true;
                proposeBtn.textContent = "提案完了";
                proposeBtn.style.background = "#6c757d";
                proposeBtn.style.cursor = "not-allowed";

                statusMsg.textContent = "✅ 曲の提案とチャット送信を完了しました！";
                statusMsg.style.color = "#198754";
            };
            contentDiv.appendChild(proposeBtn);
        }

        // ★追加: 準備が全て整ったので、ローディングを閉じる
        hideLoading();

        // 最終確認モーダルの表示
        await showModal({
            title: "🎉 抽選完了",
            contentElement: contentDiv
        });

    } catch (err) {
        hideLoading(); // ★追加: エラー時も確実に閉じる
        await showModal({ title: "エラーが発生しました", message: err.message });
    } finally {
        hideLoading(); // ★追加: 安全装置としてfinallyにも配置
        document.title = origTitle;
    }
})();
